version: "3"
services:
  restake-operator:
    image: assetmantle/restake:prod
    build: .
    labels: [com.centurylinklabs.watchtower.enable="true"]
    env_file: [.env]
    volumes: [./src/networks.local.json:/usr/src/app/src/networks.local.json:ro]

  restake-updater:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_DEBUG=true
